version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - RUNPOD_API_KEY=${RUNPOD_API_KEY}
      - RUNPOD_ENDPOINT_ID=${RUNPOD_ENDPOINT_ID}
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html

  # Optional: Local development with mock RunPod
  runpod-mock:
    build: ./runpod
    environment:
      - MODEL_ID=runwayml/stable-diffusion-v1-5
    deploy:
      resources:
        limits:
          memory: 8G
    profiles:
      - local-gpu