services:
  - type: web
    name: amlwd-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: RUNPOD_API_KEY
        sync: false
      - key: RUNPOD_ENDPOINT_ID
        sync: false
    rootDir: backend